version: 2

jobs:
  build:
    docker:
      - image: qrntz/tklc:circleci
    working_directory: ~/product
    environment:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Environment
          command: |
            jq -r '.meta.build_args | to_entries | .[] | if (.key | startswith("PRODUCT_")) then "export \(.key)=\"\(.value)\"" else empty end' manifest.json >> $BASH_ENV
            jq -r '"export BUILD_ARGS='\''" + (.meta | .build_args? | .? | to_entries | [ .[] | ("--build-arg=" + .key + "=" + .value) ] | join(" ")) + "'\''"' manifest.json >> $BASH_ENV
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker pull qrntz/keyhole-builder:master
          mkdir -p build
          if [[ -d overlay ]]; then cp -r overlay build/overlay; else mkdir -p build/overlay; fi
          mkdir -p build/overlay/usr/share/tklc/conf
          cp /usr/share/tklc/conf/* build/overlay/usr/share/tklc/conf/
          tar czf - . | docker run --name keyhole -i qrntz/keyhole-builder:master
          mkdir -p build/overlay/usr/local/sbin
          docker cp keyhole:/go/src/keyhole/keyhole ./build/overlay/usr/local/sbin/keyhole
          cat /usr/share/tklc/skel/Dockerfile.head Dockerfile.tail > ./build/Dockerfile
          docker build -t qrntz/$PRODUCT_NAME:$PRODUCT_VERSION $BUILD_ARGS build
          docker push qrntz/$PRODUCT_NAME:$PRODUCT_VERSION
